language: python
python:
  - 2.7
  - 3.4
notifications:
  email:
    - thierryschellenbach@gmail.com
env:
  # test the standalone functionality
  - DJANGO=1.6.11 CUSTOM_USER_MODEL=0 MODE=standalone REQUIREMENTS=development6 SETTINGS=facebook_example.settings TESTS=django_facebook open_facebook
  - DJANGO=1.6.11 CUSTOM_USER_MODEL=1 MODE=standalone REQUIREMENTS=development6 SETTINGS=facebook_example.settings TESTS=django_facebook open_facebook
  - DJANGO=1.7.8 CUSTOM_USER_MODEL=0 MODE=standalone REQUIREMENTS=development7 SETTINGS=facebook_example.settings TESTS=django_facebook open_facebook
  - DJANGO=1.7.8 CUSTOM_USER_MODEL=1 MODE=standalone REQUIREMENTS=development7 SETTINGS=facebook_example.settings TESTS=django_facebook open_facebook
  - DJANGO=1.8.2 CUSTOM_USER_MODEL=0 MODE=standalone REQUIREMENTS=development7 SETTINGS=facebook_example.settings TESTS=django_facebook open_facebook
  - DJANGO=1.8.2 CUSTOM_USER_MODEL=1 MODE=standalone REQUIREMENTS=development7 SETTINGS=facebook_example.settings TESTS=django_facebook open_facebook
postgres:
  adapter: sqlite3
  database: django_fb_test
install:
  # faster than installing PIL manually
  - pip install pep8 --use-mirrors
  - pip install coverage --use-mirrors
  - pip install python-coveralls --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - python setup.py install
  - pip install -r facebook_example/requirements/$REQUIREMENTS.txt --use-mirrors -I --allow-all-external
  - pip install -q Django==$DJANGO --use-mirrors -I
before_script:
  - "pep8 --exclude=south_migrations --ignore=E501,E225,W293,E731 django_facebook open_facebook"
#  - pyflakes -x W src
script:
  - pip install -e .
  - cd facebook_example
  - coverage run manage.py test $TESTS --settings=$SETTINGS -v2
after_success:
  - coveralls
